// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC04UvpdCtjnjoWl5vp-hc3mrx6OUOuaGc',
    appId: '1:349533885227:web:44d5b8bbb06837831bab6e',
    messagingSenderId: '349533885227',
    projectId: 'uncut-underground',
    authDomain: 'uncut-underground.firebaseapp.com',
    storageBucket: 'uncut-underground.appspot.com',
    measurementId: 'G-HPT89MTC0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4B0d_bmaEORF9r7g6yCsMBWusYQYxX50',
    appId: '1:349533885227:android:520e0059a55de7931bab6e',
    messagingSenderId: '349533885227',
    projectId: 'uncut-underground',
    storageBucket: 'uncut-underground.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7f-gUIBIBHgbPEbRzUZq15PYwxHiXiRE',
    appId: '1:349533885227:ios:8092a4370e9140a31bab6e',
    messagingSenderId: '349533885227',
    projectId: 'uncut-underground',
    storageBucket: 'uncut-underground.appspot.com',
    androidClientId: '349533885227-rhci7jg3669ai6e13q994kbddhlto4d1.apps.googleusercontent.com',
    iosClientId: '349533885227-3uqqr59cu1sjp13snck8uc9gpghpo11m.apps.googleusercontent.com',
    iosBundleId: 'com.example.pavegaAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7f-gUIBIBHgbPEbRzUZq15PYwxHiXiRE',
    appId: '1:349533885227:ios:8092a4370e9140a31bab6e',
    messagingSenderId: '349533885227',
    projectId: 'uncut-underground',
    storageBucket: 'uncut-underground.appspot.com',
    androidClientId: '349533885227-rhci7jg3669ai6e13q994kbddhlto4d1.apps.googleusercontent.com',
    iosClientId: '349533885227-3uqqr59cu1sjp13snck8uc9gpghpo11m.apps.googleusercontent.com',
    iosBundleId: 'com.example.pavegaAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC04UvpdCtjnjoWl5vp-hc3mrx6OUOuaGc',
    appId: '1:349533885227:web:6f4bd9007afc59941bab6e',
    messagingSenderId: '349533885227',
    projectId: 'uncut-underground',
    authDomain: 'uncut-underground.firebaseapp.com',
    storageBucket: 'uncut-underground.appspot.com',
    measurementId: 'G-7ZE0PZF8Y0',
  );
}
